Medioteca/Controllers/RoleController.cs
using Medioteca.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Medioteca.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext();
        }

        //GET: Get All Roles
       
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        


        //GET: Create  a New role

        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        //POST
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Medioteca/Controllers/SearchController.cs
using Medioteca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medioteca.Controllers
{
    public class SearchController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Search
        public ActionResult Index()
        {
            return View();
        }

        // Post: Results
        public ActionResult Results(string searchString)
        {
            //seleccionamos todos los libros que contengan en su nombre la cadena de busqueda
            var books = from m in db.Libroes select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Titulo.Contains(searchString));
            }
            //lo mismo con las peliculas
            var movies = from m in db.Peliculas select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Titulo.Contains(searchString));               
            }
            //lo mismo con las canciones
            var songs = from m in db.Cancions select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                songs = songs.Where(s => s.Titulo.Contains(searchString));
            }

            ViewBag.books   = books;
            ViewBag.movies  = movies;
            ViewBag.songs   = songs;
          
            return View();
        }


    }
}

Medioteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/fontawesome")

</head>
<body>
    <div class="navbar navbar-inverse blue-stuff navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Medioteca-OFI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><i class="fa fa-home icon-left"></i>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li><i class="fa fa-search icon-left""></i>@Html.ActionLink("Busqueda", "Index", "Search")</li>
                    <li><i class="fa fa-info-circle icon-left""></i>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li><i class="fa fa-envelope icon-left""></i>@Html.ActionLink("Roles", "Index", "Role")</li>
                    <li><i class="fa fa-user icon-left""></i>@Html.ActionLink("Users", "List", "Account")</li>
                    <li><i class="fa fa-mail-forward icon-left""></i>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>


    <div class="container body-content little_spacing shadow">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Antonio Paredes Picon para www.Ofimatica.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>